apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: devops-kit-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.240-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
