apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} #80
      targetPort: {{ .Values.service.targetPort }} #5000
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }} #5001
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
