name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335547532:role/Github_CI_Role
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 730335547532.dkr.ecr.eu-north-1.amazonaws.com/devops-kit-app
        run: |
          docker build -t $ECR_REGISTRY:latest .
          docker push $ECR_REGISTRY:latest
